import { MaterialProperties, SoftwareConfig } from '../types';

/**
 * Builds configuration objects, Python setup script for Blender,
 * and text setup guides for Blender, Unreal Engine, Unity, and V-Ray.
 */

export function generateSoftwareConfig(
  mat: MaterialProperties,
  materialFileName: string
): SoftwareConfig {
  const isDirectX = mat.normalFormat === 'DirectX';

  // 1. Blender Config & Python Script
  const blenderScript = `"""
=============================================================================
BLENDER AUTO-SETUP PBR MATERIAL SCRIPT (Blender 3.x / 4.x)
Material: ${mat.name}
Category: ${mat.category}
Generated by Seamless PBR Texture Generator 4K
=============================================================================
Instructions:
1. Save this script and your downloaded textures in the SAME folder.
2. Open Blender, go to the 'Scripting' workspace.
3. Open or paste this script and click 'Run Script' (Alt+P).
4. The material '${mat.name}' will be created with all PBR nodes linked!
=============================================================================
"""

import bpy
import os

def create_pbr_material():
    mat_name = "${mat.name.replace(/[^a-zA-Z0-9_-]/g, '_')}"
    script_dir = os.path.dirname(bpy.data.filepath) if bpy.data.is_saved else ""
    
    # Create or get material
    mat = bpy.data.materials.get(mat_name)
    if mat is None:
        mat = bpy.data.materials.new(name=mat_name)
    
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    # Output node
    output_node = nodes.new(type='ShaderNodeOutputMaterial')
    output_node.location = (600, 0)

    # Principled BSDF node
    bsdf = nodes.new(type='ShaderNodeBsdfPrincipled')
    bsdf.location = (200, 0)
    links.new(bsdf.outputs['BSDF'], output_node.inputs['Surface'])

    # Set base properties
    if hasattr(bsdf.inputs.get('IOR'), 'default_value'):
        bsdf.inputs['IOR'].default_value = ${mat.ior.toFixed(3)}
    if hasattr(bsdf.inputs.get('Metallic'), 'default_value'):
        bsdf.inputs['Metallic'].default_value = ${mat.metallic.toFixed(2)}
    if hasattr(bsdf.inputs.get('Roughness'), 'default_value'):
        bsdf.inputs['Roughness'].default_value = ${mat.baseRoughness.toFixed(2)}
    if hasattr(bsdf.inputs.get('Transmission Weight'), 'default_value'):
        bsdf.inputs['Transmission Weight'].default_value = ${(mat.transparency ?? 0).toFixed(2)}
    elif hasattr(bsdf.inputs.get('Transmission'), 'default_value'):
        bsdf.inputs['Transmission'].default_value = ${(mat.transparency ?? 0).toFixed(2)}
    if hasattr(bsdf.inputs.get('Emission Strength'), 'default_value'):
        bsdf.inputs['Emission Strength'].default_value = ${(mat.emissiveIntensity ?? 0).toFixed(2)}

    # Texture Mapping & Coordinates
    tex_coord = nodes.new(type='ShaderNodeTexCoord')
    tex_coord.location = (-1000, 0)
    mapping = nodes.new(type='ShaderNodeMapping')
    mapping.location = (-800, 0)
    links.new(tex_coord.outputs['UV'], mapping.inputs['Vector'])

    # Helper function to load texture
    def add_texture_node(filename, color_space, location, label):
        tex_node = nodes.new(type='ShaderNodeTexImage')
        tex_node.location = location
        tex_node.label = label
        filepath = os.path.join(script_dir, filename) if script_dir else filename
        if os.path.exists(filepath):
            img = bpy.data.images.load(filepath)
            img.colorspace_settings.name = color_space
            tex_node.image = img
        else:
            # Create dummy image reference so user can relink easily
            img = bpy.data.images.new(name=filename, width=1024, height=1024)
            img.colorspace_settings.name = color_space
            tex_node.image = img
        links.new(mapping.outputs['Vector'], tex_node.inputs['Vector'])
        return tex_node

    # 1. Diffuse / Base Color (sRGB)
    diff_node = add_texture_node("${materialFileName}_diffuse.jpg", 'sRGB', (-500, 400), "Base Color / Diffuse")
    links.new(diff_node.outputs['Color'], bsdf.inputs['Base Color'])

    # 2. Roughness (Non-Color)
    rough_node = add_texture_node("${materialFileName}_roughness.jpg", 'Non-Color', (-500, 150), "Roughness")
    links.new(rough_node.outputs['Color'], bsdf.inputs['Roughness'])

    # 3. Normal Map (Non-Color)
    norm_node = add_texture_node("${materialFileName}_normal.jpg", 'Non-Color', (-500, -100), "Normal Map")
    norm_map = nodes.new(type='ShaderNodeNormalMap')
    norm_map.location = (-150, -100)
    norm_map.inputs['Strength'].default_value = ${mat.normalStrength.toFixed(2)}
    links.new(norm_node.outputs['Color'], norm_map.inputs['Color'])
    links.new(norm_map.outputs['Normal'], bsdf.inputs['Normal'])

    # 4. Displacement (Non-Color)
    disp_node = add_texture_node("${materialFileName}_displacement.jpg", 'Non-Color', (-500, -350), "Displacement")
    disp_map = nodes.new(type='ShaderNodeDisplacement')
    disp_map.location = (-150, -350)
    disp_map.inputs['Scale'].default_value = ${mat.displacementScale.toFixed(3)}
    disp_map.inputs['Midlevel'].default_value = 0.5
    links.new(disp_node.outputs['Color'], disp_map.inputs['Height'])
    links.new(disp_map.outputs['Displacement'], output_node.inputs['Displacement'])

    # Set Displacement method for Cycles
    mat.cycles.displacement_method = 'BOTH' # Displacement and Bump

    print(f"Material '{mat_name}' configured successfully!")
    return mat

create_pbr_material()
`;

  return {
    blender: {
      instructions: [
        'Abra o Shading Workspace no Blender 3.x / 4.x.',
        'Selecione o seu objeto 3D e crie um novo Material Principled BSDF.',
        `Carregue '${materialFileName}_diffuse.jpg' no socket 'Base Color' (Color Space: sRGB).`,
        `Carregue '${materialFileName}_roughness.jpg' no socket 'Roughness' (Color Space: Non-Color).`,
        `Carregue '${materialFileName}_normal.jpg' através de um nó 'Normal Map' (Color Space: Non-Color) e ligue em 'Normal'.`,
        `Carregue '${materialFileName}_displacement.jpg' através de um nó 'Displacement' ligado ao 'Displacement' do Material Output (Color Space: Non-Color).`,
        'Nas configurações do Material > Settings > Surface, mude Displacement para "Displacement and Bump".',
        'Ou execute o script "setup_pbr_blender.py" incluso neste pacote para montar a árvore de nós automaticamente!'
      ],
      pythonScript: blenderScript,
      principledBsdf: {
        baseColorSpace: 'sRGB',
        normalColorSpace: 'Non-Color',
        roughnessColorSpace: 'Non-Color',
        displacementColorSpace: 'Non-Color',
        metallic: mat.metallic,
        roughness: mat.baseRoughness,
        ior: mat.ior,
        displacementScale: mat.displacementScale,
        transmission: mat.transparency ?? 0,
        emissiveIntensity: mat.emissiveIntensity ?? 0
      }
    },
    unreal: {
      instructions: [
        'Importe todos os arquivos .jpg para a pasta Content/Materials/Textures.',
        `Para '${materialFileName}_normal.jpg': Abra a textura e confirme se Compression Settings está definido como "Normalmap (DXT5/BC5)" e sRGB está DESMARCADO.`,
        isDirectX
          ? 'O Normal Map já foi gerado no padrão DirectX (Flip Green Y ativado), perfeito para a Unreal Engine!'
          : 'Nota: Caso observe iluminação invertida nas sombras, marque a opção "Flip Green Channel" nos detalhes da textura Normal.',
        `Para '${materialFileName}_roughness.jpg', '${materialFileName}_specular.jpg' e '${materialFileName}_displacement.jpg': DESMARQUE a caixa 'sRGB' (dados lineares).`,
        'No Material Editor, conecte Diffuse em Base Color, Roughness em Roughness, e Normal no socket Normal.',
        'Para Nanite Tessellation / World Position Offset: multiplique Displacement por uma scalar parameter (ex: 5 a 20 unidades) e conecte ao World Position Offset.',
        'Conecte o mapa de Ambient Occlusion no socket Ambient Occlusion do material.'
      ],
      samplerSettings: {
        diffuse: 'Linear Color: False (sRGB = True)',
        normal: 'Normalmap (BC5/DXT5), sRGB = False',
        roughness: 'Linear Grayscale, sRGB = False',
        specular: 'Linear Grayscale, sRGB = False',
        displacement: 'Linear Grayscale, sRGB = False'
      },
      compressionSettings: {
        diffuse: 'TC_Default (DXT1/DXT5)',
        normal: 'TC_Normalmap (BC5)',
        masks: 'TC_Masks ou TC_Default sem sRGB'
      },
      parameters: {
        metallic: mat.metallic,
        roughnessMultiplier: 1.0,
        specularDefault: mat.specularLevel,
        displacementScaleUnrealUnits: Math.round(mat.displacementScale * 100),
        tilingMultiplier: 1.0
      }
    },
    unity: {
      instructions: [
        'Arraste as texturas para sua pasta Assets/Textures no projeto Unity.',
        `No Inspector de '${materialFileName}_normal.jpg', mude Texture Type para 'Normal map' e clique em 'Apply'.`,
        `Para Roughness e Displacement, desmarque 'sRGB (Color Texture)' no Inspector de importação.`,
        'Crie um novo Material usando o Shader "Universal Render Pipeline/Lit" (ou HDRP/Lit).',
        `Atribua '${materialFileName}_diffuse.jpg' ao slot Base Map.`,
        'Atribua o Normal Map ao slot Normal Map e ajuste a escala de Bump se necessário.',
        'No URP (Workflow Metallic/Smoothness): inverta a Roughness para Smoothness (ou atribua no canal Alpha do Metallic map).',
        'Atribua o mapa de Displacement no slot Height Map e ajuste a amplitude de altura.',
        'Atribua o mapa de AO no slot Occlusion.'
      ],
      pipeline: 'URP',
      workflow: 'Metallic/Smoothness',
      textureImportSettings: {
        diffuse: 'Texture Type: Default, sRGB: Enabled, Generate Mip Maps: True',
        normal: 'Texture Type: Normal Map, Create from Greyscale: False',
        roughness: 'Texture Type: Default, sRGB: Disabled (Linear)',
        specular: 'Texture Type: Default, sRGB: Disabled',
        displacement: 'Texture Type: Default, sRGB: Disabled (Linear)'
      },
      materialParams: {
        workflow: 'Metallic',
        metallic: mat.metallic,
        smoothness: (1.0 - mat.baseRoughness).toFixed(2),
        normalScale: mat.normalStrength,
        heightAmplitude: mat.displacementScale
      }
    },
    vray: {
      instructions: [
        'Crie um material do tipo VRayMtl no 3ds Max, Maya ou Cinema 4D.',
        `Conecte '${materialFileName}_diffuse.jpg' no canal 'Diffuse'.`,
        `Conecte '${materialFileName}_roughness.jpg' no canal 'Reflect Roughness' (se usar modo Roughness) ou inverta para 'Reflect Glossiness'.`,
        `Conecte '${materialFileName}_specular.jpg' no canal 'Reflect Color' com Fresnel IOR = ${mat.ior.toFixed(3)}.`,
        `Conecte '${materialFileName}_normal.jpg' através de um VRayNormalMap no slot 'Bump / Normal' com Map Type = Normal Map (Tangent Space).`,
        `Para deslocamento volumétrico, aplique o modificador 'VRayDisplacementMod' na malha e conecte '${materialFileName}_displacement.jpg' como Texmap 2D/3D com Amount entre ${mat.displacementScale.toFixed(3)} e ${(mat.displacementScale * 2).toFixed(3)}.`
      ],
      vrayMtlSettings: {
        diffuseColor: 'Mapped from diffuse.jpg',
        reflectionColor: 'Fresnel IOR ' + mat.ior.toFixed(3),
        roughnessMode: 'Microfacet GTR (GGX)',
        baseRoughness: mat.baseRoughness,
        metalness: mat.metallic,
        bumpMapType: 'VRayNormalMap (Tangent)',
        bumpMult: mat.normalStrength
      },
      displacementModifier: {
        type: 'VRayDisplacementMod 2D/3D',
        amount: mat.displacementScale * 10.0,
        shift: -mat.displacementScale * 5.0,
        resolution: 2048
      }
    }
  };
}

/**
 * Generates the unified comprehensive human-readable TXT documentation file
 * required by the user's prompt.
 */
export function generateUnifiedTextDoc(
  mat: MaterialProperties,
  materialFileName: string,
  cfg: SoftwareConfig,
  resolution: number
): string {
  return `================================================================================
GUIA DE CONFIGURAÇÃO PBR MULTI-SOFTWARE (BLENDER, V-RAY, UNITY, UNREAL ENGINE)
================================================================================
Material: ${mat.name}
Categoria: ${mat.category.toUpperCase()}
Resolução: ${resolution}x${resolution} (Seamless Tileable 4K/2K/1K)
Formato das Texturas: JPEG de Alta Qualidade (95% Quality)
Normal Map Space: Tangent Space (${mat.normalFormat})
IOR Físico: ${mat.ior.toFixed(3)} | Metalicidade: ${mat.metallic.toFixed(2)} | Rugosidade Média: ${mat.baseRoughness.toFixed(2)}
Transparência (Transmission): ${((mat.transparency ?? 0) * 100).toFixed(0)}% | Emissão (Glow): ${(mat.emissiveIntensity ?? 0).toFixed(2)}x
================================================================================

LISTA DE ARQUIVOS INCLUÍDOS NO PACOTE:
--------------------------------------------------------------------------------
1. ${materialFileName}_diffuse.jpg       -> Mapa de Difusão / Albedo (Base Color)
2. ${materialFileName}_specular.jpg      -> Mapa de Especular (Reflectance F0)
3. ${materialFileName}_normal.jpg        -> Mapa de Normais (Normal Map Tangent Space)
4. ${materialFileName}_roughness.jpg     -> Mapa de Rugosidade (Microrrugosidade de Superfície)
5. ${materialFileName}_displacement.jpg  -> Mapa de Deslocamento / Altura (Height / Displacement)
6. ${materialFileName}_ao.jpg            -> Mapa de Oclusão Ambiental (Ambient Occlusion)
7. setup_pbr_blender.py                  -> Script Python para automação 1-clique no Blender
8. material_settings.json                -> Especificações técnicas em formato JSON
9. MATERIAL_CONFIG_BLENDER_VRAY_UNITY_UNREAL.txt -> Este guia de configuração rápida

================================================================================
1. BLENDER (Cycles & EEVEE Next) - CONFIGURAÇÃO RECOMENDADA
================================================================================
MÉTODO AUTOMÁTICO (RÁPIDO):
1. Coloque o script "setup_pbr_blender.py" na mesma pasta das texturas.
2. No Blender, abra a aba "Scripting", abra o arquivo e pressione "Run Script".
3. O material completo com todas as conexões será criado automaticamente!

MÉTODO MANUAL:
- Nó Principal: Shader Principled BSDF
- ${materialFileName}_diffuse.jpg       -> Conectar em "Base Color" (Color Space: sRGB)
- ${materialFileName}_roughness.jpg     -> Conectar em "Roughness" (Color Space: Non-Color)
- ${materialFileName}_normal.jpg        -> Conectar em Nó "Normal Map" -> "Normal" (Color Space: Non-Color)
  * Normal Map Strength: ${mat.normalStrength.toFixed(2)}
- ${materialFileName}_displacement.jpg  -> Conectar em Nó "Displacement" -> "Displacement" do Material Output (Color Space: Non-Color)
  * Midlevel: 0.500 | Scale: ${mat.displacementScale.toFixed(3)}
- IOR: ${mat.ior.toFixed(3)}
- Metallic: ${mat.metallic.toFixed(2)}
- Para deslocamento real na viewport (Cycles):
  Material Properties > Settings > Surface > Displacement: selecionar "Displacement and Bump".

================================================================================
2. UNREAL ENGINE 5 (Lumen, Nanite & Master Material)
================================================================================
IMPORTAÇÃO DE TEXTURAS:
- Arraste todos os .jpg para Content/Textures.
- ${materialFileName}_diffuse.jpg:
  * sRGB: MARCADO (True)
  * Compression: TC_Default (DXT1/5)
- ${materialFileName}_normal.jpg:
  * sRGB: DESMARCADO (False)
  * Compression: TC_Normalmap (BC5)
  * Nota: O mapa foi gerado no formato ${mat.normalFormat}.
- ${materialFileName}_roughness.jpg:
  * sRGB: DESMARCADO (Linear)
  * Compression: TC_Default ou TC_Masks
- ${materialFileName}_displacement.jpg:
  * sRGB: DESMARCADO (Linear)
- ${materialFileName}_ao.jpg:
  * sRGB: DESMARCADO (Linear)

CONEXÃO NO MATERIAL GRAPH:
- Diffuse -> Base Color
- Roughness -> Roughness
- Specular -> Specular (valor base: ${mat.specularLevel.toFixed(2)})
- Normal -> Normal
- AO -> Ambient Occlusion
- Displacement -> Multiplicar por Scalar Parameter (ex: 5 a 20) -> World Position Offset (com Nanite Tessellation ativada na UE 5.3+).

================================================================================
3. UNITY (URP - Universal Render Pipeline & HDRP)
================================================================================
CONFIGURAÇÃO DO INSPECTOR DE TEXTURAS:
- ${materialFileName}_normal.jpg:
  * Texture Type: Normal map
  * Create from Greyscale: Desmarcado
- ${materialFileName}_roughness.jpg & displacement.jpg:
  * Texture Type: Default
  * sRGB (Color Texture): DESMARCADO (Linear)

MATERIAL LIT (URP / HDRP):
- Surface Type: Opaque
- Workflow: Metallic
- Base Map: ${materialFileName}_diffuse.jpg
- Metallic: ${mat.metallic.toFixed(2)}
- Smoothness: ${(1.0 - mat.baseRoughness).toFixed(2)} (Unity utiliza Smoothness = 1 - Roughness)
- Normal Map: ${materialFileName}_normal.jpg (Scale: ${mat.normalStrength.toFixed(2)})
- Height Map: ${materialFileName}_displacement.jpg (Amplitude: ${mat.displacementScale.toFixed(3)})
- Occlusion: ${materialFileName}_ao.jpg

================================================================================
4. V-RAY (3ds Max, Maya, SketchUp, Cinema 4D)
================================================================================
MATERIAL V-RAY MTL:
- Diffuse: ${materialFileName}_diffuse.jpg
- Reflect: ${materialFileName}_specular.jpg (ou cinza RGB 60 com Fresnel IOR ${mat.ior.toFixed(3)})
- Reflect Roughness (GGX): ${materialFileName}_roughness.jpg (inverta caso use modo Glossiness)
- Bump / Normal Map:
  * Slot: Bump
  * Tipo: VRayNormalMap
  * Imagem: ${materialFileName}_normal.jpg (Tangent Space)
  * Mult: ${mat.normalStrength.toFixed(2)}
- Deslocamento de Superfície:
  * Aplicar modificador "VRayDisplacementMod" no objeto.
  * Tipo: 2D ou 3D Mapping
  * Texmap: ${materialFileName}_displacement.jpg
  * Amount: ${(mat.displacementScale * 10).toFixed(2)} cm
  * Shift: ${(-mat.displacementScale * 5).toFixed(2)} cm

================================================================================
NOTAS TÉCNICAS E CRÉDITOS
================================================================================
- Textura 100% Seamless / Sem Emendas gerada com interpolação de borda contínua.
- Pode ser repetida (Tiled) infinitamente em qualquer eixo (U e V) sem cortes perceptíveis.
- Compatível com PBR Metal/Roughness e PBR Specular/Glossiness pipelines.
================================================================================
`;
}
